// @ts-check
import { defineConfig } from "astro/config";

import tailwindcss from "@tailwindcss/vite";

import react from "@astrojs/react";

import mdx from "@astrojs/mdx";

// https://astro.build/config
export default defineConfig({
  // Required for canonical URLs and the sitemap to use the real domain
  // instead of http://localhost.
  site: "https://mehedi.engineer",

  base: "/",

  image: {
    // The project card is generated by socialify. Allowing the host makes
    // Astro fetch it during the build and emit a hashed copy into _astro/,
    // so visitors are served from this domain — no runtime request to a third
    // party — and the card's star/fork counts refresh on every build.
    remotePatterns: [{ protocol: "https", hostname: "socialify.git.ci" }],
  },

  build: {
    // Site CSS is small (~14 KB) — inline it to remove a render-blocking
    // request and shorten the CSS -> font critical chain on mobile.
    inlineStylesheets: "always",
  },

  vite: {
    plugins: [tailwindcss()],
  },

  integrations: [react(), mdx()],
});
